module.exports = {
	curly: ["error", "multi-line"],
	eqeqeq: ["error", "always", { null: "ignore" }],
	strict: "error",
	yoda: ["error", "never"],
	"accessor-pairs": "error",
	"array-bracket-spacing": ["error", "never"],
	"arrow-parens": ["error", "as-needed", { requireForBlockBody: false }],
	"arrow-spacing": ["error", { before: true, after: true }],
	"block-spacing": ["error", "always"],
	"brace-style": ["error", "1tbs", { allowSingleLine: true }],
	"comma-dangle": ["error", { arrays: "always-multiline", objects: "always-multiline", imports: "always-multiline", exports: "always-multiline", functions: "never" }],
	"comma-spacing": ["error", { before: false, after: true }],
	"comma-style": ["error", "last"],
	"computed-property-spacing": ["error", "never"],
	"dot-location": ["error", "property"],
	"eol-last": ["error", "never"],
	"func-call-spacing": ["error", "never"],
	"function-paren-newline": "off",
	"generator-star-spacing": ["error", "after"],
	"guard-for-in": "error",
	"handle-callback-err": ["error", "^(e|err|error)$"],
	"key-spacing": ["error", { beforeColon: false, afterColon: true }],
	"keyword-spacing": ["error", { before: true, after: true }],
	"new-parens": "error",
	"no-array-constructor": "error",
	"no-caller": "error",
	"no-constant-condition": ["error", { checkLoops: false }],
	"no-eval": "error",
	"no-extend-native": "error",
	"no-extra-bind": "error",
	"no-extra-parens": "error",
	"no-floating-decimal": "error",
	"no-implied-eval": "error",
	"no-iterator": "error",
	"no-label-var": "error",
	"no-labels": ["error", { allowLoop: false, allowSwitch: false }],
	"no-lone-blocks": "error",
	"no-mixed-operators": "off",
	"no-multi-spaces": "error",
	"no-multi-str": "error",
	"no-multiple-empty-lines": ["error", { max: 1, maxEOF: 0 }],
	"no-negated-in-lhs": "error",
	"no-nested-ternary": "off",
	"no-new-func": "error",
	"no-new-object": "error",
	"no-new-require": "error",
	"no-new-wrappers": "error",
	"no-new": "error",
	"no-octal-escape": "error",
	"no-param-reassign": "off",
	"no-path-concat": "error",
	"no-proto": "error",
	"no-return-assign": "off",
	"no-return-await": "error",
	"no-self-compare": "error",
	"no-sequences": "error",
	"no-template-curly-in-string": "error",
	"no-trailing-spaces": "error",
	"no-undef-init": "error",
	"no-unmodified-loop-condition": "error",
	"no-unneeded-ternary": ["error", { defaultAssignment: false }],
	"no-unused-vars": ["error", { vars: "all", args: "all", argsIgnorePattern: "^_", ignoreRestSiblings: true, caughtErrors: "all", caughtErrorsIgnorePattern: "^_" }],
	"no-use-before-define": ["error", { functions: false, classes: false, variables: false }],
	"no-useless-call": "error",
	"no-useless-computed-key": "error",
	"no-useless-constructor": "error",
	"no-useless-rename": "error",
	"no-useless-return": "error",
	"no-var": "error",
	"no-whitespace-before-property": "error",
	"object-property-newline": "off",
	"object-shorthand": "error",
	"one-var": ["error", { initialized: "never" }],
	"operator-linebreak": ["error", "after", { overrides: { "?": "before", ":": "before" } }],
	"padded-blocks": ["error", { blocks: "never", switches: "never", classes: "never" }],
	"prefer-arrow-callback": "error",
	"prefer-const": "error",
	"prefer-destructuring": "off",
	"prefer-named-capture-group": "off",
	"prefer-numeric-literals": "error",
	"prefer-object-spread": "error",
	"prefer-promise-reject-errors": "error",
	"prefer-reflect": "off",
	"prefer-rest-params": "error",
	"prefer-spread": "error",
	"prefer-template": "error",
	"quote-props": ["error", "as-needed", { keywords: false, unnecessary: true, numbers: false }],
	"rest-spread-spacing": ["error", "never"],
	"semi-spacing": ["error", { before: false, after: true }],
	"space-before-blocks": ["error", "always"],
	"space-before-function-paren": ["error", { anonymous: "always", named: "never", asyncArrow: "always" }],
	"space-in-parens": ["error", "never"],
	"space-infix-ops": "error",
	"space-unary-ops": ["error", { words: true, nonwords: false }],
	"spaced-comment": ["error", "always", { line: { markers: ["/"], exceptions: ["-", "+"] }, block: { markers: ["!"], exceptions: ["*"], balanced: true } }],
	"symbol-description": "error",
	"template-curly-spacing": ["error", "never"],
	"template-tag-spacing": ["error", "never"],
	"unicode-bom": ["error", "never"],
	"wrap-iife": ["error", "any", { functionPrototypeMethods: true }],
	"yield-star-spacing": ["error", "after"],
};